### ISSUE TITLE
[BUG] Syntax Highlighting for Ansible URI module, Body in data format throws syntax error

### ISSUE THREAD

**Issue by kenmaglio** [redhat-developer/yaml-language-server#103]
if in an ansible playbook, you specify and use the URI module, and specify the body as a data format, the syntax highlighting throws an error stating 'String' expected.

This will produce an error

```
body_format: json
body:
  dl:
    table_type: dl
    date: "{{ lookup('pipe', 'date -d ' + date_variance + ' +\"%Y-%m-%d\"') }}"
```
