### ISSUE TITLE
Feature request: let me apply an ad-hoc inline schema to a block

### ISSUE THREAD

**Issue by jwhitaker-gridcog** [redhat-developer/yaml-language-server#1030]
### Is your enhancement related to a problem? Please describe.

It would be useful if I could apply a JSON/yaml schema to an arbitrary part of my document.
For example, let's say I'm writing a `kustomization.yaml` that instantiates a Helm chart:
```yaml
helmCharts:
  - repo: https://charts.jetstack.io
    name: cert-manager
    namespace: cert-manager
    version: v1.17.0
    includeCRDs: true
    releaseName: cert-manager
    valuesInline: # !! <-- there is actually a values.schema.json in the chart, but I have no way of hooking it up to here where I need it
      crds:
        enabled: true
```

### Describe the solution you would like

Some syntax to let me hook this up in an ad-hoc way. Arbitrary example:

```yaml
helmCharts:
  - ...
    valuesInline:
      # $schema=./charts/cert-manager-v1.17.0/cert-manager/values.schema.json
      crds:
        enabled: true
```
