### ISSUE TITLE
List identation is off for the last item in the list if another property exists below it

### ISSUE THREAD

**Issue by nickjj** [redhat-developer/yaml-language-server#1047]
## Describe the bug

I hope this is the right repo to report this in. I am using Neovim and `:LspInfo` says this LSP is responsible for doing code formatting.

I'm going to include a reproduceable example here, `|` is going to represent your cursor. You can do this in a file called `demo.yaml`:

```yaml
hello:
  - a|

world: {}
```

If you hit enter and type `-` to start the next item in the list you end up with this:

```yaml
hello:
  - a
- b

world: {}
```

The expectation is:

```yaml
hello:
  - a
  - b

world: {}
```

A couple of notes:

- If `world: {}` doesn't exist, then the indentation is correct
- If the item is not the last item in the list (such as the middle, etc.) then the indentation is correct as long as the last item's indentation matches the first item

## Environment
- [ ] Windows
- [ ] Mac
- [X] Linux
- [ ] other (please specify)
