### ISSUE TITLE
Using `bool` values in `enum` and `const` generates a validation error for valid values

### ISSUE THREAD

**Issue by Kosta-Github** [redhat-developer/yaml-language-server#1078]
## Describe the bug

When using a `boolean` value in an `enum` schema (e.g.: `enum: [true]`) validation fails for a valid value.

The error message is: `Value is not accepted. Valid values: true.`

For example, the `OpenAPI 3.0` spec is using such a mechanism in its schema.

## Expected Behavior

The schema validation should pass without an issue.

## Current Behavior

The schema validation generates this error message: `Value is not accepted. Valid values: true.`

<img width="577" alt="Image" src="https://github.com/user-attachments/assets/37fd4722-9fc1-44cd-a8dc-ca94253e0f35" />

## Steps to Reproduce

Place these 2 files next to each other:

`schema.yaml`:
```yaml
$schema: "http://json-schema.org/draft-07/schema#"
type: object
properties:
  value:
    enum: [true]
```

`test.yaml`:
```yaml
# yaml-language-server: $schema=./schema.yaml

value: true
```

## Environment

- [ ] Windows
- [x] Mac
- [ ] Linux
- [ ] other (please specify)

Latest version of the extension: `1.18.0`

**Comment by Kosta-Github** [comment]
BTW, a similar error is created if using `boolean` in a `const`:

<img width="493" alt="Image" src="https://github.com/user-attachments/assets/f4fba6a9-41eb-46c6-a568-d5a876d4e489" />

## Steps to Reproduce

Place these 2 files next to each other:

`schema.yaml`:
```yaml
$schema: "https://json-schema.org/draft/2020-12/schema"
type: object
properties:
  value:
    const: true
```

`test.yaml`:
```yaml
# yaml-language-server: $schema=./schema.yaml

value: true
```
