### ISSUE TITLE
Usage with Multiple Schemas in a File?

### ISSUE THREAD

**Issue by mahyarmirrashed** [redhat-developer/yaml-language-server#1082]
## Summary

I'm doing something like this:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  ...
spec:
  ...
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  ...
spec:
  ...
```

I'm using [schema-companion.nvim](https://github.com/cenk1cenk2/schema-companion.nvim) to dynamically set the schema.

I'm wondering what I would need to change in there so that we have proper schema matching when there is the `---` document separator in the YAML files? Currently, the schema is being applied to the whole file, and that's not what I want.

I don't want to have to put modelines everywhere as well.

Suggestions or clarifications would be great.
