### ISSUE TITLE
Offset of undefined

### ISSUE THREAD

**Issue by JPinkney** [redhat-developer/yaml-language-server#162]
On master branch doing
```
apiVersion: v1
metadata:
  name: test
kind: Deployment
spec:
  selector:
    
  template:
    
```
and hovering over spec yields cannot read offset of undefined error
