### ISSUE TITLE
Support Recursive Self Referencing JSON-Schema

### ISSUE THREAD

**Issue by tsangpo** [redhat-developer/yaml-language-server#200]
JSON-Schema like this one won't be valid now.

```json
{
  "type": "object",
  "properties": {
    "name": { "type": "string" },
    "tree": { "$ref": "#/definitions/tree" }
  },
  "definitions": {
    "tree": {
      "type": "object",
      "properties": {
        "value": { "type": "string" },
        "branches": {
          "type": "array",
          "items": { "$ref": "#/definitions/tree" },
          "minItems": 1
        }
      },
      "required": ["value"]
    }
  }
}
```

**Comment by JPinkney** [comment]
I've just tried out that schema with the latest release and everything seems to be working:

```YAML
name: name
tree:
  value: asd
  branches:
    - value: asd
      branches:
        - value: asd
          branches:
            - value: asd
```

If there are any other issues let me know
