### ISSUE TITLE
'defaultSnippets' support has some bugs

### ISSUE THREAD

**Issue by evidolob** [redhat-developer/yaml-language-server#225]
When snippet provided in `defaultSnippets` has array of some objects, JSON array not correctly converted to yaml:
```yaml
      name: 
      taskRef: 
        name: apply-manifests
      
      resources: 
        inputs: 
          0: 
            name: source
            resource: 
          
        
      
      params: 
        0: 
          name: manifest_dir
          value: 
        
      
```
it inserts `0:` instead of `-`.

Also when snippet inserted from completion form called after `- ` (space `-` ) snippet lost some format:
```yaml
    - name: 
    taskRef: name: apply-manifests
    
    resources: inputs: 0: name: source
    resource: 
    
    
    
    params: 0: name: manifest_dir
    value: 
    
    
``` 

Snippet used in `defaultSnippets`:
```json
  {
    "label": "apply-manifests",
    "description": "Task",
    "body": {
      "name": "$1",
      "taskRef": {
        "name": "apply-manifests"
      },
      "resources": {
        "inputs": [
          {
            "name": "source",
            "resource": "$3"
          }
        ]
      },
      "params": [
        {
          "name": "manifest_dir",
          "value": "$2"
        }
      ]
    }
  }
```

Demo:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/929743/72998350-5d0bc600-3e06-11ea-8299-24c014d841d8.gif)

**Comment by evidolob** [comment]
@JPinkney I still have problems with this issue:
When I do completion on some completion item provided with `defaultSnippets`, it inserts :

```yaml
  name: 
      taskRef: 
        name: buildah-v0-8-0
        kind: ClusterTask  
      resources: 
        inputs: 
          
          name: source
          resource:         
        outputs: 
          
          name: image
          resource:           
      params: 
        
        name: BUILDER_IMAGE
        value:   
        
        name: DOCKERFILE
        value:   
        
        name: TLSVERIFY
        value:     
```
But it should insert: 
```yaml
  name: 
      taskRef: 
        name: buildah-v0-8-0
        kind: ClusterTask  
      resources: 
        inputs: 
          - name: source
             resource: 
        outputs:
          - name: image
             resource:          
      params: 
        - name: BUILDER_IMAGE
           value:d
        - name: DOCKERFILE
           value: 
        - name: TLSVERIFY
           value: 
```
Snippet used for this example:
```json
{
              "label": "buildah-v0-8-0",
              "description": "ClusterTask",
              "body": {
                "name": "$1",
                "taskRef": {
                  "name": "buildah-v0-8-0",
                  "kind": "ClusterTask"
                },
                "resources": {
                  "inputs": [
                    {
                      "name": "source",
                      "resource": "$5"
                    }
                  ],
                  "outputs": [
                    {
                      "name": "image",
                      "resource": "$6"
                    }
                  ]
                },
                "params": [
                  {
                    "name": "BUILDER_IMAGE",
                    "value": "$2"
                  },
                  {
                    "name": "DOCKERFILE",
                    "value": "$3"
                  },
                  {
                    "name": "TLSVERIFY",
                    "value": "$4"
                  }
                ]
              }
            }
```
Full scheme:
https://gist.github.com/evidolob/2cb80710b8dc239677715e10c90e2d7b
