### ISSUE TITLE
Region folding works incorrectly with commented lines

### ISSUE THREAD

**Issue by Leon99** [redhat-developer/yaml-language-server#242]
Once a line inside a region is commented, the region won't fold past that line - only the part before the commented line is folded. In the example below, level23 will remain unfolded on folding level1:
``` yaml
level1:
  level21:
#   level22:
  level23:
```
