### ISSUE TITLE
Ansible Package - Incorrect Type Expected String

### ISSUE THREAD

**Issue by shawnweeks** [redhat-developer/yaml-language-server#289]
For some reason it doesn't like this but Ansible runs the command without issue so the syntax appears to be valid.

See https://docs.ansible.com/ansible/latest/modules/package_module.html

```
- name: "Install Required Packages"
  package:
    name:
      - sudo
      - tar
      - unzip
      - gzip
    state: present
```
