### ISSUE TITLE
Bug: autogenerated snippet for keys that contain an array of objects is badly indented

### ISSUE THREAD

**Issue by fbaligand** [redhat-developer/yaml-language-server#329]
When I validate auto-completion for a key that contain an array of objects, the snippet generated contains 2 extra spaces for each sub-key generated.

Here's an example in `kubernetes.yml`:

Given that I have this file content:
```
metadata:
    ownerReferences
```
Then I go to end of `ownerReferences`, press `Ctrl+Tab` and `[ENTER]` to validate the suggested completion.  
I get this result:
```
metadata:
    ownerReferences:
        - apiVersion: 
            kind: 
            name: 
            uid: 
```

The problem is that "kind", "name" and "uid" keys have 2 extra spaces in front.
