### ISSUE TITLE
Auto completing an object underneath an array can produce the wrong indentation

### ISSUE THREAD

**Issue by JPinkney** [redhat-developer/yaml-language-server#392]
## Describe the bug

Auto completing an object underneath an array can produce the wrong indentation

## Expected Behavior

```yaml
test_array_anyOf_2objects:
  - obj2:
      | <- indent here
```

## Current Behavior

```yaml
test_array_anyOf_2objects:
  - obj2:
    | <- indent here
```

## Steps to Reproduce

1. Use https://raw.githubusercontent.com/redhat-developer/yaml-language-server/252c1e83c99394d2536b58c08057e2d37d3b7187/test/fixtures/testArrayCompletionSchema.json as the schema
2. Use this yaml and try to autocomplete
```yaml
test_array_anyOf_2objects:
  - | <- auto complete here
```
3. See that you get current behavior and not expected behavior

## Environment
- [ ] Windows
- [ ] Mac
- [X] Linux
- [ ] other (please specify)
