### ISSUE TITLE
Folding misbehaves in version 0.14.0

### ISSUE THREAD

**Issue by benbridts** [redhat-developer/yaml-language-server#400]
## Describe the bug
When using this code, folding does not work as expected:

```
FirstDict:
  FirstDictFirstKey:
    SomeList:
      - foo
SecondDict:
  SecondDictFirstKey: foo
```

## Expected Behavior
When clicking the carret before `FirstDictFirstKey`, only the things under FirstDictFirstKey should be folded

## Current Behavior
One line extra collapses. `SecondDict` will dissapear.

![image](https://user-images.githubusercontent.com/1301221/106290562-e8eed400-624a-11eb-9b20-87ccc3e94ee9.png)

## Steps to Reproduce
1. Use the provided code
2. Fold `FirstDictFirstKey`

Note: Removing the list from the file makes this behavior stop.

## Environment
- [ ] Windows
- [X] Mac
- [ ] Linux
- [ ] other (please specify)
