### ISSUE TITLE
Helm conditional and loop expressions

### ISSUE THREAD

**Issue by derba** [redhat-developer/yaml-language-server#449]
Helm, the leading cloud native application delivery and configuration management solution, has its templating syntax. I think its support could be improved.

Lets consider this file, copied from [here](https://helm.sh/docs/chart_template_guide/control_structures/):

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  drink: {{ .Values.favorite.drink | default "tea" | quote }}
  food: {{ .Values.favorite.food | upper | quote }}
  {{- if eq .Values.favorite.drink "coffee" }}
  mug: true
  {{- end }}
```
In VS Code on the line of `if` the following problem is printed: "missed comma between flow collection entries".
On the next line with "mug" this appears: "end of the stream or a document separator is expected".
Both are incorrect.

Sometimes, for the sake of easier readability, the conditional and loop lines are not indented according to YAML. E.g:

```yaml
data:
{{- if eq .Values.favorite.drink "coffee" }}
  mug: true
{{- else }}
  cup: true
{{- end }}
```

Probably the easiest solution would be ignoring anything between `{{` and `}}`.
