### ISSUE TITLE
"Billion Laughs" attack yaml breaks language server

### ISSUE THREAD

**Issue by evidolob** [redhat-developer/yaml-language-server#463]
## Describe the bug
Related to https://github.com/kubernetes/kubernetes/issues/83253 

Yaml 

```yaml
apiVersion: v1
data:
  a: &a ["web","web","web","web","web","web","web","web","web"]
  b: &b [*a,*a,*a,*a,*a,*a,*a,*a,*a]
  c: &c [*b,*b,*b,*b,*b,*b,*b,*b,*b]
  d: &d [*c,*c,*c,*c,*c,*c,*c,*c,*c]
  e: &e [*d,*d,*d,*d,*d,*d,*d,*d,*d]
  f: &f [*e,*e,*e,*e,*e,*e,*e,*e,*e]
  g: &g [*f,*f,*f,*f,*f,*f,*f,*f,*f]
  h: &h [*g,*g,*g,*g,*g,*g,*g,*g,*g]
  i: &i [*h,*h,*h,*h,*h,*h,*h,*h,*h]
kind: ConfigMap
metadata:
  name: yaml-bomb
  namespace: default
```

Coease a huge cpu load and vscode reports that yaml language server failed to launch 5 times.

It seems that [new parser ](https://github.com/redhat-developer/yaml-language-server/pull/442) wasn't  affected but it requires double check. 

## Expected Behavior
LS work normally

## Current Behavior
LS crushed

## Steps to Reproduce

1. Just put provided yaml sample in editor
2.
3. 

## Environment
- [ ] Windows
- [x] Mac
- [ ] Linux
- [ ] other (please specify)
