### ISSUE TITLE
Does the yaml server support the Kube  kind: List    from apiVersion: v1

### ISSUE THREAD

**Issue by kramvan1** [redhat-developer/yaml-language-server#490]
## Summary

Simple kube `kind: List` from apiVersion `v1` does not seem supported, why is that?   It's used everywhere.

## Relevant information
```
apiVersion: v1
kind: List
metadata:
  name: mylist
items:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: myjob
      namespace: mynamsspace
```
