### ISSUE TITLE
Kubernetes apiVersion of extensions is not supoported

### ISSUE THREAD

**Issue by tdabasinskas** [redhat-developer/yaml-language-server#58]
It seems that the following YAML file for a cert-manager configuration is not supported (getting `Value is not accepted. Valid values: "v1"`):

```yaml
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
...
```

It also seems to be the case with other extension versions, e.g. [`certificates./v1beta1`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#certificatesigningrequest-v1beta1-certificates) and [`extensions/v1beta1`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#ingress-v1beta1-extensions).

**Comment by thearrow** [comment]
Running into the same thing on Kubernetes Ingress resources:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
[...]
```

> Value is not accepted. Valid values: "v1beta1".
