### ISSUE TITLE
Completion does not work for the first property of a nested object

### ISSUE THREAD

**Issue by sfalmo** [redhat-developer/yaml-language-server#616]
## Describe the bug
In nested objects, property completion of the first property item does not work. While the completion shows suggestions if it is triggered before typing anything, no suggestions are shown during typing.
For consecutive property items, completion does work again as expected.

## Expected Behavior
Suitable suggestions should also be shown when parts of the first property of the inner object are typed.

## Current Behavior
No completion suggestions are shown, completion has to be triggered manually before writing property.

## Steps to Reproduce
Use the following schema and create a `parent` object that contains e.g. `child1`. Then try to type the first property of `child1`.
```yaml
$schema: http://json-schema.org/draft-07/schema
title: Test nested completion
description: Test schema for completion of properties in nested objects
type: object
properties:
  parent:
    type: object
    properties:
      child1:
        type: object
        properties:
          prop1:
            type: string
          prop2:
            type: string
          prop3:
            type: string
      child2:
        type: object
        properties:
          prop1:
            type: string
          prop2:
            type: string
          prop3:
            type: string
```

![first](https://user-images.githubusercontent.com/52037539/145246301-755f3e09-0d4d-4770-aad1-941a392c1f89.png)

![second](https://user-images.githubusercontent.com/52037539/145246350-1ae5211d-2534-48d3-8789-0ae9104ca036.png)

Completion can be triggered manually if nothing has been typed yet:

![manual](https://user-images.githubusercontent.com/52037539/145246361-5e4e2063-6da4-44f1-b4a7-f768562f4274.png)

## Environment
- [ ] Windows
- [ ] Mac
- [x] Linux
- [ ] other (please specify)
