### ISSUE TITLE
List indention can break Visual Studio Code suggestions

### ISSUE THREAD

**Issue by EmilySeville7cfg** [redhat-developer/yaml-language-server#646]
## Describe the bug

> Cursor is shown as `<cursor>`.

`prop2` expected to be shown instead of `{} - (array item)`:

```yml
- prop1: value
  object:
  - env_prop1: value
  <cursor>
```

![image](https://user-images.githubusercontent.com/42812113/150460540-4bc5058b-77fb-49e4-83d2-4cd8185ff572.png)

The workaround is to use indention:

```yml
- prop1: value
  object:
    - env_prop1: value
  <cursor>
```

![image](https://user-images.githubusercontent.com/42812113/150460921-c2e0fd0c-7a4d-4aac-afa9-708399a77bfd.png)

## Expected Behavior

`prop2` to be always shown.

## Current Behavior

Missing list indention breaks suggestion.

## Steps to Reproduce

Create a JSON schema:

```json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "title": "Sample schema",

    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "prop1": {
                "type": "string"
            },
            "prop2": {
                "type": "string"
            },
            "object": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "env_prop1": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}
```

Create `.vscode/settings.json`:

```json
{
    "yaml.schemas": {
        "schema.json": "input.yml"
    }
}
```

Create `input.yml`:

```yml
- prop1: value
  object:
  - env_prop1: value
  <cursor>
```

Call autocomplete via `Ctrl`+`Space`.

## Environment
- [ ] Windows
- [ ] Mac
- [x] Linux 
- [ ] other (please specify)

```
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:39:46.686Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.0-96-generic
```
