### ISSUE TITLE
LSP formatting not getting applied

### ISSUE THREAD

**Issue by robbyki** [redhat-developer/yaml-language-server#657]
lsp formatter not getting applied with below settings:
```
  lspconfig.yamlls.setup({
     on_attach = on_attach,
      capabilities = capabilities,
      filetypes = { "yml", "yaml", "yaml.docker-compose", "config" },
      settings = { 
          yaml = {
▎             format = { enable = true },
▎             validate = true,
▎             completion = true,
▎             hover = true,
              schemas = {
                  ["http://json.schemastore.org/github-workflow"] = ".github/workflows/*.{yml,yaml}",
                  ["http://json.schemastore.org/github-action"] = ".github/action.{yml,yaml}",
                  ["http://json.schemastore.org/ansible-stable-2.9"] = "roles/tasks/*.{yml,yaml}",
                  ["http://json.schemastore.org/prettierrc"] = ".prettierrc.{yml,yaml}",
                  ["http://json.schemastore.org/kustomization"] = "kustomization.{yml,yaml}",
                  ["http://json.schemastore.org/ansible-playbook"] = "*play*.{yml,yaml}",
                  ["http://json.schemastore.org/chart"] = "Chart.{yml,yaml}",
                  ["https://json.schemastore.org/dependabot-v2"] = ".github/dependabot.{yml,yaml}",
                  ["https://json.schemastore.org/gitlab-ci"] = "*gitlab-ci*.{yml,yaml}",
                  ["https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.1/schema.json"] = "*api*.{yml,yaml
                  ["https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json"] = "docker-compos
▎                 ["https://raw.githubusercontent.com/robbyki/schemas/1f05c98df4ca8398f502f554734ff5e87acfcc4c/openshift/all.json"
                  ["https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.23.1-standalone-strict/all.json"] = "
                  kubernetes = "/*.yaml",
            },
          },
      },
  })

```
![Peek 2022-02-05 07-15](https://user-images.githubusercontent.com/1027357/152641846-101207fb-826e-4948-9bb2-0baa17143f59.gif)

**Comment by remcohaszing** [comment]
Prettier can only format valid YAML. The content in the gif has a syntax error (`replicas` and `strategy` need to have the same indentation).

**Comment by robbyki** [comment]
I might be misunderstanding how to enable the default formatter perhaps. This is not getting formatted either (note the extra space in `replicas`):
```
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: busybox
spec:
  replicas    : 1 
  selector:
    name: busybox
  template:
    metadata:
      labels:
        name: busybox
    spec:
      containers:
      - name: busybox
        image: dockerfile/busybox
        command:
        - sleep
        - "3600"
```
