### ISSUE TITLE
Server returning nothing on things such as completion errors Eclipse Che

### ISSUE THREAD

**Issue by JPinkney** [redhat-developer/yaml-language-server#66]
```yaml
kind: PersistentVolume
apiVersion: v1
metadata: <- Autocompletion right after :
```
returns 

```
[Trace - 16:51:10] Received response 'textDocument/completion - (48)' in 1ms.
No result returned.
```
but should return 

```
Result: {
    "items": [],
    "isIncomplete": false
}
```

Part of: https://github.com/eclipse/che/issues/9725
