### ISSUE TITLE
Serverless Framework - Variable substitutions

### ISSUE THREAD

**Issue by tle-finder** [redhat-developer/yaml-language-server#734]
## Summary

Serverless framework allows for string substitutions that the language server cannot reasonably be expected to verify. 

Unsure how to configure the language server to skip the following errors.

## Relevant information

The following is from a serverless framework template:

```yaml
provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: python3.8
  region: ap-southeast-2
  vpc: "${self:custom.${self:custom.stage}.provider.vpc}".       ■ Incorrect type. Expected "Aws.Vpc".
```

What can I do to remove the above "Incorrect type" warning.

Also, why wouldn't the substitution at `stage` cause the same issue?

The relevant schema is: https://raw.githubusercontent.com/lalcebo/json-schema/master/serverless/reference.json
