### ISSUE TITLE
Description not returned on hover when using yaml anchors

### ISSUE THREAD

**Issue by balki** [redhat-developer/yaml-language-server#737]
## Describe the bug

When hovering over foo's place, description appears but not on bar's place

### Input yaml

```
title: meetup
refs:
  place: &default_place NYC
users:
  - name: foo
    place: SFC
  - name: bar
    place: *default_place

# yaml-language-server: $schema=./schema.yaml

```

### Schema
```
$schema: http://json-schema.org/draft/2020-12/schema
additionalProperties: false
properties:
    title:
        description: Title of this file
        type: string
    refs:
        type: object
    users:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
              description: Name of the user
            place:
              type: string
              description: Place of residence

```

### Language server stdin

```
{"method":"textDocument/hover","jsonrpc":"2.0","id":2,"params":{"textDocument":{"uri":"file:///path/to/input.yaml"},"position":{"character":4,"line":5}}}Content-Length: 197

{"method":"textDocument/hover","jsonrpc":"2.0","id":3,"params":{"textDocument":{"uri":"file:///path/to/input.yaml"},"position":{"character":4,"line":7}}}Content-Length: 44

```

### Language server stdout

```
{"jsonrpc":"2.0","id":2,"result":{"contents":{"kind":"markdown","value":"Place of residence\n\nSource: [schema.yaml](file:///path/to/schema.yaml)"},"range":{"start":{"line":5,"character":4},"end":{"line":5,"character":9}}}}Content-Length: 151

{"jsonrpc":"2.0","id":3,"result":{"contents":{"kind":"markdown","value":""},"range":{"start":{"line":7,"character":4},"end":{"line":7,"character":9}}}}Content-Length: 38

```

## Expected Behavior
Return description value

## Current Behavior
Returns empty string

## Steps to Reproduce
1. Hover over the property which has a yaml anchor as value

## Environment
- [X] Linux
