### ISSUE TITLE
Inconsistent behavior with inlined schemas

### ISSUE THREAD

**Issue by someone-stole-my-name** [redhat-developer/yaml-language-server#777]
## Describe the bug

When using the inlined schemas the behavior is different vs when the schema is defined in the settings.

## Expected Behavior

The behavior should be the same, doesn't matter if the user sets the schema inline or in configuration.

## Current Behavior

The diagnostics do not work or are different.

## Steps to Reproduce

1. Start with a blank config and create a file with the following content:

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.22.4-standalone-strict/all.json
apiVersion: networking.k8s.io/v1
kind: Ingress
foo: bar
```
It doesn't trigger any diagnostics but autocompletion works.

2. Configure the schema to apply to all YAML files in the settings:

```json
{
    "yaml.schemas": {
        "https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.22.4-standalone-strict/all.json": "/*.yaml"
    }
}
```

Create a file with the following content:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
foo: bar
```

It triggers the expected diagnostics: 

- `Property foo is not allowed.yaml-schema: https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.22.4-standalone-strict/_definitions.json`

## Environment
- [ ] Windows
- [x] Mac
- [x] Linux
- [ ] other (please specify)
