### ISSUE TITLE
Getting customTags to work

### ISSUE THREAD

**Issue by tim3trick** [redhat-developer/yaml-language-server#797]
## Summary
I have nvim (astrovim) set up and running and am currently trying to work on some partial gitlab-ci yaml file.
Currently I get the error "Unresolved tag !reference".

## Relevant information
Here is the content of the file in question:

```
# yaml-language-server $schema=https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json
feature:build:
  stage: build
  variables:
    DOCKER_TAG: $CI_COMMIT_REF_SLUG
  script:
    - !reference [".deploy", script]
```
`!reference` is a valid custom tag for gitlab-ci

This is my current yamlls configuration (init.lua):
```
      yamlls = {
        settings = {
          yaml = {
            schemastore = {
              enable = true,
            },
            customTags = {
              "!reference scalar",
            },
          },
        },
      },
```
I tried various versions, including 

- changing cases
- using `!reference scalar`, `!reference mapping`, `!reference sequence` and just `!reference` 
- `customtags` instead of `customTags` (had to do this for `schemastore` to get it to work)

If i disable validation via 
```
        settings = {
          yaml = {
            validate = false,
```
The error is gone, so I suspect that the configuration is passed to yamlls.

Can someone help me out?
