### ISSUE TITLE
incorrect behavior of keys with quotes

### ISSUE THREAD

**Issue by Dimus99** [redhat-developer/yaml-language-server#798]
when autocomplete keys with quotes are not put quotes

schema:
```
additionalProperties: false
properties:
  validation:
    type: object
    additionalProperties: false
    properties:
      "null":
        type: boolean
        default: false
```

behavior:

https://user-images.githubusercontent.com/47976394/198999985-5cb36793-e5fb-4ee9-bf86-f0a0b12dc15f.mov

## Expected Behavior
The key will be inserted with quotes

## Current Behavior
the key is sometimes inserted without quotes

## Environment
- [ ] Windows
- [+] Mac
- [ ] Linux
- [ ] other (please specify)
