### ISSUE TITLE
Support multiple ressources with different schemas in kubernetes files

### ISSUE THREAD

**Issue by victornoel** [redhat-developer/yaml-language-server#80]
With kubernetes, it is possible to have multiple resources in one file, separated by `---`.

Currently, if the resources have different `apiVersion`, we get the following errors for each `apiVersion`:
```
Matches multiple schemas when only one must validate.
```

I think the language server should be able to handle this situation.

**Comment by JPinkney** [comment]
Can you post the YAML? That isn't actually an error per se its just saying there are multiple sub schemas inside of the Kubernetes schema it matches so therefore it doesn't know which one to verify against.

**Comment by victornoel** [comment]
@JPinkney here is one:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: nginx
      volumes:
        - name: config-volume
          configMap:
            name: app-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  config: some config
```

Let's call it a feature request then: the editor should be able to apply the schema up to the next `---` :)
