### ISSUE TITLE
`Matches a schema that is not allowed` error, but the ansible-playbook script runs fine.

### ISSUE THREAD

**Issue by David-Else** [redhat-developer/yaml-language-server#836]
Hi,

My first attempt to use ansible has been thwarted by red squiggles.

I have installed this language server and am using the Helix editor that works with it out-of-the-box. My first script works running `ansible-playbook` , but I am told `Matches a schema that is not allowed`, and I have looked at the Helix logs and it seems to be using the correct https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json

```yml
- name: Bootstrap development environment
  hosts: localhost

  tasks:
  - name: Install Stow on redhat clones
    become: true
    dnf:
      name:
        - stow
      state: present
```
![Screenshot from 2023-01-20 16-48-36](https://user-images.githubusercontent.com/12832280/213755903-efc3cb35-c53e-405e-b580-94bbf8afa539.png)
![Screenshot from 2023-01-20 16-50-07](https://user-images.githubusercontent.com/12832280/213756256-820730a0-8050-4c7b-aa0f-5d2d3320ecab.png)

What exactly does this message mean? It doesn't really make sense, does it mean `ansible.json` is not allowed? What can I do about this problem? I would like it to help me with ansible. 

Also I have no formatting available, it is turned of by default? That would be a strange choice? Cheers.
