### ISSUE TITLE
Type errors inform wrong type when parent schema has keyword "title"

### ISSUE THREAD

**Issue by nieomylnieja** [redhat-developer/yaml-language-server#845]
## Describe the bug
It seems that using the `title` keyword propagates the element name to all it's properties which also have a `type` of `object`.
I verified the behaviour against another JSON Schema implementation: https://www.jsonschemavalidator.net/.
Given the following schema:

```yaml
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "file:///home/mh/schema/test.schema.json",
  "type": "object",
  "title": "THE OBJECT",
  "properties": {
    "foo": {
      "type": "object"
    },
    "bar": {
      "type": "string"
    }
  }
}
```

It produced the following error:
![2023-02-14_17-23](https://user-images.githubusercontent.com/48822818/218798417-d38b0bcb-327f-401d-9921-951877185a6c.png)
Which makes absolute sense, since the type of the property `foo` is `object`.
However that's not the case with yaml-language-server, which instead treats all `type` errors for `object` properties of a schema with set `title` keyword as If they had the same type as the parent schema, i.e. `THE OBJECT`.
![2023-02-14_17-24](https://user-images.githubusercontent.com/48822818/218799244-2944715d-1c44-4508-9547-66f8a8c11a72.png)
It only happens when the property is of type `object`, If we now change `bar` to an invalid type, let's say `object` it will produce the right error, telling us it should be a string:
![2023-02-14_17-34](https://user-images.githubusercontent.com/48822818/218799837-a992cb3f-1fad-418c-af44-e4dc3eebaab3.png)

## Expected Behavior
Displayed error should be referring to the property `type`, not the parent schema `type`.

## Current Behavior
Displayed error informs about parent schema `type`, instead of the property `type` mismatch.

## Steps to Reproduce
Copy the schema provided in the description and play around with it as described.

## Environment
- [ ] Windows
- [ ] Mac
- [x] Linux
- [ ] other (please specify)
