### ISSUE TITLE
TypeError: Cannot create property 'url' on string 'object'

### ISSUE THREAD

**Issue by rameshx** [redhat-developer/yaml-language-server#916]
## Describe the bug

I'm using [monaco-yaml](https://github.com/remcohaszing/monaco-yaml) with [react-monaco-editor](https://github.com/react-monaco-editor/react-monaco-editor), and I'm seeing the below error in the console and validation, schema-based suggestions are not working. The error is also displayed every time the YAML is edited.

```
TypeError: Cannot create property 'url' on string 'object'
    at _validateObjectNode (https://localhost:8181/yaml.worker.a42e65.js:36085:32)
    at validate2 (https://localhost:8181/yaml.worker.a42e65.js:35533:7)
    at testAlternatives (https://localhost:8181/yaml.worker.a42e65.js:35610:9)
    at _validateNode (https://localhost:8181/yaml.worker.a42e65.js:35654:7)
    at validate2 (https://localhost:8181/yaml.worker.a42e65.js:35547:3)
    at _validateObjectNode (https://localhost:8181/yaml.worker.a42e65.js:36087:13)
    at validate2 (https://localhost:8181/yaml.worker.a42e65.js:35533:7)
    at SingleYAMLDocument.validate (https://localhost:8181/yaml.worker.a42e65.js:35478:7)
    at getDiagnostics (https://localhost:8181/yaml.worker.a42e65.js:34011:47)
    at https://localhost:8181/yaml.worker.a42e65.js:34048:16
```

YAML:

```
template:
  name: yaml validation error template
  identifier: yaml_validation_error_template
  versionLabel: "1"
  type: Step
  projectIdentifier: test
  orgIdentifier: default
  tags: {}
  spec:
    type: Wait
    spec:
      duration: 10m
```

Schema: https://raw.githubusercontent.com/harness/harness-schema/dc42a2b54209b66a635734d4fa8b891a7903a63f/v0/template.json

## Expected Behavior
Features like code completion, validation, etc., work as expected

## Current Behavior
Seeing errors related to validation in the console 

## Environment
- [ ] Windows
- [x] Mac
- [ ] Linux
- [ ] other (please specify)
