### ISSUE TITLE
YAML `---` for "Multiple documents within a single stream" doesn't work [YAML Language Server]

### ISSUE THREAD

**Issue by vorburger** [redhat-developer/yaml-language-server#946]
[Originally reported as https://github.com/redhat-developer/vscode-yaml/issues/995, before I understood this really belongs more here.]

I wrote my first trivial JSON schema `enola.schema.jsonc`, like this:

```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://docs.enola.dev/json-schema/enola_meta.schema.jsonc",
  "title": "Enola.dev Meta Model",
  "description": "See https://docs.enola.dev",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "name": {
      "type": "string",
      "description": "Short technical name of this Type."
    }
  },
  "required": ["name"]
}
```

Then I wrote an `test.yaml` file using that schema, like this:

```yaml
# yaml-language-server: $schema=enola.schema.jsonc

name: enola.dev/url
doc: enola.md#URL

---
name: enola.dev/id
doc: enola.md#ID
```

## Current Behavior

It does put a "red squiggle" on the first `doc: enola.md#URL` but not on the second `doc: enola.md#ID`.

In fact the 2nd `name: enola.dev/id` doesn't have the "hover" with the `description`from the schema either.

It looks like the YAML `---` syntax for _"multiple documents within a single stream"_ isn't supported / doesn't work?

## Expected Behavior

I expected it to flag the `doc` attribute as red in both my _URL_ and _ID_ attributes.

**Comment by AnhQuanTrl** [comment]
I also encounter the same issue using Neovim. It seems like this is a regression. Multidoc used to work as far as I remember.

**Comment by ionous** [comment]
this previously resolved issue might be related: #16  ( _Multiple YAML documents in single file features work for first section but not the rest_  )
and there is also this currently open issue #869  ( _intellisense completion breaks with multiple documents in a single file_  )

**Comment by thieman** [comment]
Is this only applying when using the `# yaml-language-server` inline directive to specify the schema? I think that's intended behavior in that it only applies to the YAML document (not the entire file) it's a part of. If you copy `# yaml-language-server: $schema=enola.schema.jsonc` into the second document, do you start seeing autocompletion etc work as expected? It's working that way for me currently in VSCode.

**Comment by AnhQuanTrl** [comment]
@thieman It used to work on my end with multiple `# yaml-language-server` per YAML document. However, this is no longer the case and the top `# yaml-language-server` affects the whole file instead of a document.

**Comment by nikaro** [comment]
It happens to me without using the inline `# yaml-language-server` directive.

**Comment by thieman** [comment]
Ah ok, it seems like we have at least two different things being reported here? Please let me know if any of this is wrong.

@vorburger is saying that the current behavior is inline directives only apply to the document, not the file. I am also experiencing this.

@AnhQuanTrl is saying the opposite! That the inline directives apply to the entire file.

@nikaro could you elaborate on your issue, or let us know if it fits into one of the other descriptions?

Could you all please report your version numbers? I'm using the VSCode extension at v1.15.0, which is also using the language server at 1.15.0.

**Comment by nikaro** [comment]
@thieman sorry i ended up following this issue as its title seemed more aligned with my issue. But it fits more with the comments on this one: https://github.com/redhat-developer/yaml-language-server/issues/869

I'm using Helix editor with yaml-language-server version 1.15.0.

<img width="960" alt="Capture d’écran 2024-08-28 à 15 53 07" src="https://github.com/user-attachments/assets/f225fff6-df5e-4ace-a9c5-7e19bf0a815c">

**Comment by fredleger** [comment]
same wit zed and yls

**Comment by datho7561** [comment]
> same wit zed and yls

Which version of the language server is Zed using?

Which of the above errors are you facing? I was able to get validation working properly if I added the comment to each document in the file eg.

```yaml
# yaml-language-server: $schema=enola.schema.jsonc

name: enola.dev/url
doc: enola.md#URL

---
# yaml-language-server: $schema=enola.schema.jsonc

name: enola.dev/id
doc: enola.md#ID
```

**Comment by fredleger** [comment]
v1.22.0 bundled in zed extension i guess.
for me specifying comment on each doc does not seem to work around the issue

<img width="1216" height="1036" alt="Image" src="https://github.com/user-attachments/assets/9e9bf4cb-3709-4228-8407-855d3ee3dee1" />

Note: Only the second docs is marked as invalid, 3rd and 4th etc.. does not (but i believe the parsing stops at 1st error on this topic)

**Comment by datho7561** [comment]
Seems to be working for me?

<img width="436" height="369" alt="Image" src="https://github.com/user-attachments/assets/110f6d12-54a0-418e-8c24-f0fe97583817" />

**Comment by datho7561** [comment]
I also tried with kubernetes specifically. `settings.json`:

```jsonc
"lsp": {
    "yaml-language-server": {
      "settings": {
        "yaml": {
          "schemas": {
            "kubernetes": "*.k8s.yaml"
          }
        }
      }
    },
  },
```

Validate against two different Kubernetes objects:

```yaml
---
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
spec:
  secretName: pant
  service:
    defaultPort: mysql-rw
    type: ClusterIP
    aaa: hjkl
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: foo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: foo
  minReplicas: 2
  maxReplicas: 3
  foo: bar
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
```

Works fine:

<img width="398" height="704" alt="Image" src="https://github.com/user-attachments/assets/ab3c66bc-2e20-46fe-ac0f-6775b1f57d67" />
