### ISSUE TITLE
Support def pointers in url with `schema.json#ref=RefName`

### ISSUE THREAD

**Issue by airtonix** [redhat-developer/yaml-language-server#988]
### Is your enhancement related to a problem? Please describe.

my `schema.json`: 

```json
{
  "$defs": {

    "IncludeAThing": {
      "properties": {
        "include": {
          "type": "string"
        }
      },
      "required": [
        "include"
      ],
      "title": "IncludeAThing",
      "type": "object"
    },

    "ABigThing": {
      "properties": {
        "thing": {
          "$ref": "#/$defs/AThing"
        }
      },
      "required": [
        "thing"
      ],
      "title": "ABigThing",
      "type": "object"
    },

    "AListOfThings": {
      "items": {
        "anyOf": [
          {
            "$ref": "#/$defs/AThing"
          },
          {
            "$ref": "#/$defs/IncludeAThing"
          },
          {
            "$ref": "#/$defs/ABigThing"
          }
        ]
      },
      "title": "AListOfThings",
      "type": "array"
    },

    "AThing": {
      "properties": {
        "name": {
          "type": "string"
        },
      },
      "required": [
        "name"
      ],
      "title": "AThing",
      "type": "object"
    },
  },
  "properties": {
    "things": {
        "$ref": "AListOfThings
    }
  },
  "required": [
    "things",
  ],
  "title": "ASchemaOfThings",
  "type": "object"
}
```

so i might have : 

`config.yml`
```yml
# yaml-language-server: $schema=./schema.json

things: 
  - include: "./some-include.yml"
  - thing:
      name: "The Thing!"
  - name: "Moar things!"
```

`./some-include.yml`

```yml
- name: "All
- name: "The"
- name: "Things"
```

I want to be able to do : 

`./some-include.yml`

```yml
# yaml-language-server: $schema=./schema.json#$ref=AListOfThings

- name: "All
- name: "The"
- name: "Things"
```

### Describe the solution you would like

allow me to specify that a yaml file be validated by a ref pointer of an existing schema.

### Describe alternatives you have considered

Giving up software and becoming a farmer.

### Additional context

n/a
